#######################################################################
#                                                                     #
# TEMPLATE MAKEFILE                                                   #
# Rename this file to 'Makefile' and put in target's directory        #
#                                                                     #
#######################################################################

#
# TARGET
#

#   - Target name
TARGET_NAME=common

#   - Target type: lib, dll, exe, klib, kdrv
TARGET_TYPE=lib

#   - Target dependencies
TARGET_DEPENDS=

#   - Target include directories
#     Don't add include directory for SDK/WDK/Dependencies
TARGET_INCDIRS=

#   - Target library directories
#     Don't add include directory for SDK/WDK/Dependencies
TARGET_LIBDIRS=

#   - Libraries to be linked
TARGET_LIBS=

#   - Libraries to be linked
TARGET_PCH=

TARGET_SRCS= \
	src/util.cpp \
	src/version.cpp


#########################################
#	MASTER MAKEFILE						#
#	NO TARGET SETTINGS BELOW THIS LINE	#
#########################################
# Include master Makefile
include $(XBUILDROOT)/make/xmake_master_target.mak