if(NOT XBUILD_PLATFORM_WIN32)
    message(FATAL_ERROR "xbuild-platform-windows: XBUILD_PLATFORM_WIN32 is not set")
endif()

# Set common data
set(XBUILD_PLATFORM_DESKTOP ON)
if(XBUILD_PLATFORM_BITS64)
    set(XBUILD_PLATFORM_ARCH "x86_64")
else()
    set(XBUILD_PLATFORM_ARCH "x86")
endif()

if(DURANGO)
    set(XBUILD_PLATFORM_DURANGO ON)
    add_definitions(-DXBUILD_PLATFORM_DURANGO)
    set(XBUILD_PLATFORM_STRING "Durango")
elseif(WINDOWS_STORE)
    set(XBUILD_PLATFORM_UWP ON)
    add_definitions(-DXBUILD_PLATFORM_UWP)
    set(XBUILD_PLATFORM_STRING "UWP")
else()
    add_definitions(-DXBUILD_PLATFORM_WIN32)
    if(XBUILD_PLATFORM_BITS64)
        set(XBUILD_PLATFORM_STRING "Win64")
    else()
        set(XBUILD_PLATFORM_STRING "Win32")
    endif()
endif()

set(CMAKE_CONFIGURATION_TYPES "Debug;Optimized;Release" CACHE STRING "" FORCE)
